// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inspection.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInspection = `-- name: CreateInspection :one

INSERT INTO inspections (port_call_id, inspection_date, result, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, port_call_id, inspection_date, result, notes, created_at, updated_at
`

type CreateInspectionParams struct {
	PortCallID     int64       `json:"port_call_id"`
	InspectionDate pgtype.Date `json:"inspection_date"`
	Result         string      `json:"result"`
	Notes          *string     `json:"notes"`
}

// Queries de Inspection para o sqlc.
// Registra uma inspeção PSC vinculada a um port call.
// A constraint UNIQUE em port_call_id garante no máximo uma inspeção por escala.
func (q *Queries) CreateInspection(ctx context.Context, arg CreateInspectionParams) (Inspection, error) {
	row := q.db.QueryRow(ctx, createInspection,
		arg.PortCallID,
		arg.InspectionDate,
		arg.Result,
		arg.Notes,
	)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.PortCallID,
		&i.InspectionDate,
		&i.Result,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInspectionByPortCall = `-- name: GetInspectionByPortCall :one
SELECT id, port_call_id, inspection_date, result, notes, created_at, updated_at FROM inspections WHERE port_call_id = $1
`

// Retorna a inspeção de um port call, se existir.
// Retorna pgx.ErrNoRows se o port call ainda não foi inspecionado.
func (q *Queries) GetInspectionByPortCall(ctx context.Context, portCallID int64) (Inspection, error) {
	row := q.db.QueryRow(ctx, getInspectionByPortCall, portCallID)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.PortCallID,
		&i.InspectionDate,
		&i.Result,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
