// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inspection struct {
	ID             int64              `json:"id"`
	PortCallID     int64              `json:"port_call_id"`
	InspectionDate pgtype.Date        `json:"inspection_date"`
	Result         string             `json:"result"`
	Notes          *string            `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PortCall struct {
	ID                int64              `json:"id"`
	VesselID          int64              `json:"vessel_id"`
	Berth             *string            `json:"berth"`
	VesselStatus      string             `json:"vessel_status"`
	PortCallStatus    string             `json:"port_call_status"`
	EtaDate           pgtype.Date        `json:"eta_date"`
	EtaTime           pgtype.Time        `json:"eta_time"`
	EtdDate           pgtype.Date        `json:"etd_date"`
	EtdTime           pgtype.Time        `json:"etd_time"`
	ActualArrival     pgtype.Timestamptz `json:"actual_arrival"`
	ActualDeparture   pgtype.Timestamptz `json:"actual_departure"`
	RiskLevelSnapshot *string            `json:"risk_level_snapshot"`
	PrioritySnapshot  *string            `json:"priority_snapshot"`
	Zp21Sourced       bool               `json:"zp21_sourced"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Terminal          *string            `json:"terminal"`
	LastZp21SeenAt    pgtype.Timestamptz `json:"last_zp21_seen_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Vessel struct {
	ID                         int64              `json:"id"`
	Imo                        *string            `json:"imo"`
	Name                       string             `json:"name"`
	Flag                       *string            `json:"flag"`
	YearBuilt                  *int32             `json:"year_built"`
	VesselType                 *string            `json:"vessel_type"`
	LengthM                    pgtype.Numeric     `json:"length_m"`
	BeamM                      pgtype.Numeric     `json:"beam_m"`
	RiskLevel                  *string            `json:"risk_level"`
	LastInspectionDate         pgtype.Date        `json:"last_inspection_date"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	LastInspectionDeficiencies *string            `json:"last_inspection_deficiencies"`
	Afretado                   bool               `json:"afretado"`
	Acompanhado                bool               `json:"acompanhado"`
}
