// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: port_call.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBerthing = `-- name: CancelBerthing :exec
UPDATE port_calls
SET actual_arrival      = NULL,
    actual_departure    = NULL,
    vessel_status       = 'navigating',
    port_call_status    = 'planned',
    risk_level_snapshot = NULL,
    priority_snapshot   = NULL,
    updated_at          = NOW()
WHERE id = $1
`

// Cancela a atracação: limpa actual_arrival, actual_departure e snapshots.
// Alerta: também apaga dados de suspensão — o front-end deve avisar o usuário.
func (q *Queries) CancelBerthing(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, cancelBerthing, id)
	return err
}

const cancelSuspension = `-- name: CancelSuspension :exec
UPDATE port_calls
SET actual_departure    = NULL,
    port_call_status    = 'active',
    risk_level_snapshot = NULL,
    priority_snapshot   = NULL,
    updated_at          = NOW()
WHERE id = $1
`

// Cancela a suspensão: limpa actual_departure e reverte escala para ativa.
func (q *Queries) CancelSuspension(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, cancelSuspension, id)
	return err
}

const createPortCall = `-- name: CreatePortCall :one
INSERT INTO port_calls (
    vessel_id, terminal, vessel_status, port_call_status,
    eta_date, eta_time, etd_date, etd_time, zp21_sourced
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, vessel_id, berth, vessel_status, port_call_status, eta_date, eta_time, etd_date, etd_time, actual_arrival, actual_departure, risk_level_snapshot, priority_snapshot, zp21_sourced, created_at, updated_at, terminal
`

type CreatePortCallParams struct {
	VesselID       int64       `json:"vessel_id"`
	Terminal       *string     `json:"terminal"`
	VesselStatus   string      `json:"vessel_status"`
	PortCallStatus string      `json:"port_call_status"`
	EtaDate        pgtype.Date `json:"eta_date"`
	EtaTime        pgtype.Time `json:"eta_time"`
	EtdDate        pgtype.Date `json:"etd_date"`
	EtdTime        pgtype.Time `json:"etd_time"`
	Zp21Sourced    bool        `json:"zp21_sourced"`
}

// Cria um novo port call a partir do scraper ZP-21.
// risk_level_snapshot e priority_snapshot são preenchidos depois (via CIALA).
func (q *Queries) CreatePortCall(ctx context.Context, arg CreatePortCallParams) (PortCall, error) {
	row := q.db.QueryRow(ctx, createPortCall,
		arg.VesselID,
		arg.Terminal,
		arg.VesselStatus,
		arg.PortCallStatus,
		arg.EtaDate,
		arg.EtaTime,
		arg.EtdDate,
		arg.EtdTime,
		arg.Zp21Sourced,
	)
	var i PortCall
	err := row.Scan(
		&i.ID,
		&i.VesselID,
		&i.Berth,
		&i.VesselStatus,
		&i.PortCallStatus,
		&i.EtaDate,
		&i.EtaTime,
		&i.EtdDate,
		&i.EtdTime,
		&i.ActualArrival,
		&i.ActualDeparture,
		&i.RiskLevelSnapshot,
		&i.PrioritySnapshot,
		&i.Zp21Sourced,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Terminal,
	)
	return i, err
}

const deletePortCall = `-- name: DeletePortCall :exec
DELETE FROM port_calls WHERE id = $1
`

// Remove uma escala. Falha com FK error se houver inspeção vinculada.
func (q *Queries) DeletePortCall(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePortCall, id)
	return err
}

const getActivePortCallByVessel = `-- name: GetActivePortCallByVessel :one
SELECT id, vessel_id, berth, vessel_status, port_call_status, eta_date, eta_time, etd_date, etd_time, actual_arrival, actual_departure, risk_level_snapshot, priority_snapshot, zp21_sourced, created_at, updated_at, terminal, last_zp21_seen_at FROM port_calls
WHERE vessel_id = $1
  AND (port_call_status = 'planned' OR port_call_status = 'active')
ORDER BY created_at DESC
LIMIT 1
`

// Retorna o port call mais recente com status planned ou active para um vessel.
// Usado pelo scraper para decidir se deve criar ou atualizar.
func (q *Queries) GetActivePortCallByVessel(ctx context.Context, vesselID int64) (PortCall, error) {
	row := q.db.QueryRow(ctx, getActivePortCallByVessel, vesselID)
	var i PortCall
	err := row.Scan(
		&i.ID,
		&i.VesselID,
		&i.Berth,
		&i.VesselStatus,
		&i.PortCallStatus,
		&i.EtaDate,
		&i.EtaTime,
		&i.EtdDate,
		&i.EtdTime,
		&i.ActualArrival,
		&i.ActualDeparture,
		&i.RiskLevelSnapshot,
		&i.PrioritySnapshot,
		&i.Zp21Sourced,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Terminal,
		&i.LastZp21SeenAt,
	)
	return i, err
}

const getEscala = `-- name: GetEscala :one
SELECT
    pc.id, pc.vessel_id, pc.terminal,
    pc.eta_date, pc.etd_date,
    pc.actual_arrival, pc.actual_departure,
    pc.vessel_status, pc.port_call_status,
    pc.risk_level_snapshot, pc.priority_snapshot,
    v.name AS vessel_name, v.imo AS vessel_imo,
    v.flag AS vessel_flag, v.afretado AS vessel_afretado, v.acompanhado AS vessel_acompanhado,
    v.risk_level AS vessel_risk_level,
    v.last_inspection_date AS vessel_last_inspection_date
FROM port_calls pc
JOIN vessels v ON v.id = pc.vessel_id
WHERE pc.id = $1
`

type GetEscalaRow struct {
	ID                       int64              `json:"id"`
	VesselID                 int64              `json:"vessel_id"`
	Terminal                 *string            `json:"terminal"`
	EtaDate                  pgtype.Date        `json:"eta_date"`
	EtdDate                  pgtype.Date        `json:"etd_date"`
	ActualArrival            pgtype.Timestamptz `json:"actual_arrival"`
	ActualDeparture          pgtype.Timestamptz `json:"actual_departure"`
	VesselStatus             string             `json:"vessel_status"`
	PortCallStatus           string             `json:"port_call_status"`
	RiskLevelSnapshot        *string            `json:"risk_level_snapshot"`
	PrioritySnapshot         *string            `json:"priority_snapshot"`
	VesselName               string             `json:"vessel_name"`
	VesselImo                *string            `json:"vessel_imo"`
	VesselFlag               *string            `json:"vessel_flag"`
	VesselAfretado           bool               `json:"vessel_afretado"`
	VesselAcompanhado        bool               `json:"vessel_acompanhado"`
	VesselRiskLevel          *string            `json:"vessel_risk_level"`
	VesselLastInspectionDate pgtype.Date        `json:"vessel_last_inspection_date"`
}

// Retorna uma escala pelo ID com dados do navio.
func (q *Queries) GetEscala(ctx context.Context, id int64) (GetEscalaRow, error) {
	row := q.db.QueryRow(ctx, getEscala, id)
	var i GetEscalaRow
	err := row.Scan(
		&i.ID,
		&i.VesselID,
		&i.Terminal,
		&i.EtaDate,
		&i.EtdDate,
		&i.ActualArrival,
		&i.ActualDeparture,
		&i.VesselStatus,
		&i.PortCallStatus,
		&i.RiskLevelSnapshot,
		&i.PrioritySnapshot,
		&i.VesselName,
		&i.VesselImo,
		&i.VesselFlag,
		&i.VesselAfretado,
		&i.VesselAcompanhado,
		&i.VesselRiskLevel,
		&i.VesselLastInspectionDate,
	)
	return i, err
}

const getPortCallByID = `-- name: GetPortCallByID :one
SELECT id, vessel_id, berth, vessel_status, port_call_status, eta_date, eta_time, etd_date, etd_time, actual_arrival, actual_departure, risk_level_snapshot, priority_snapshot, zp21_sourced, created_at, updated_at, terminal, last_zp21_seen_at FROM port_calls WHERE id = $1
`

func (q *Queries) GetPortCallByID(ctx context.Context, id int64) (PortCall, error) {
	row := q.db.QueryRow(ctx, getPortCallByID, id)
	var i PortCall
	err := row.Scan(
		&i.ID,
		&i.VesselID,
		&i.Berth,
		&i.VesselStatus,
		&i.PortCallStatus,
		&i.EtaDate,
		&i.EtaTime,
		&i.EtdDate,
		&i.EtdTime,
		&i.ActualArrival,
		&i.ActualDeparture,
		&i.RiskLevelSnapshot,
		&i.PrioritySnapshot,
		&i.Zp21Sourced,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Terminal,
		&i.LastZp21SeenAt,
	)
	return i, err
}

const abortStaleZP21PortCalls = `-- name: AbortStaleZP21PortCalls :exec
UPDATE port_calls
SET port_call_status = 'aborted', updated_at = NOW()
WHERE zp21_sourced = TRUE
  AND port_call_status = 'planned'
  AND (last_zp21_seen_at IS NULL OR last_zp21_seen_at < $1)
`

// Cancela escalas ZP-21 planejadas que não apareceram na última consulta.
func (q *Queries) AbortStaleZP21PortCalls(ctx context.Context, scrapeTime pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, abortStaleZP21PortCalls, scrapeTime)
	return err
}

const getStaleBerthedPortCalls = `-- name: GetStaleBerthedPortCalls :many
SELECT pc.id, pc.vessel_id,
       v.name AS vessel_name,
       v.risk_level, v.last_inspection_date
FROM port_calls pc
JOIN vessels v ON v.id = pc.vessel_id
WHERE pc.zp21_sourced = TRUE
  AND pc.port_call_status = 'active'
  AND pc.vessel_status = 'berthed'
  AND (pc.last_zp21_seen_at IS NULL OR pc.last_zp21_seen_at < $1)
  AND pc.terminal IS NOT NULL
  AND EXISTS (
      SELECT 1 FROM port_calls pc2
      WHERE pc2.id != pc.id
        AND pc2.vessel_status = 'berthed'
        AND pc2.port_call_status = 'active'
        AND pc2.terminal = pc.terminal
  )
`

type GetStaleBerthedPortCallsRow struct {
	ID                 int64       `json:"id"`
	VesselID           int64       `json:"vessel_id"`
	VesselName         string      `json:"vessel_name"`
	RiskLevel          *string     `json:"risk_level"`
	LastInspectionDate pgtype.Date `json:"last_inspection_date"`
}

// Retorna escalas ativas+atracadas que sumiram do ZP-21 e têm outro navio no mesmo terminal (R5).
func (q *Queries) GetStaleBerthedPortCalls(ctx context.Context, scrapeTime pgtype.Timestamptz) ([]GetStaleBerthedPortCallsRow, error) {
	rows, err := q.db.Query(ctx, getStaleBerthedPortCalls, scrapeTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStaleBerthedPortCallsRow{}
	for rows.Next() {
		var i GetStaleBerthedPortCallsRow
		if err := rows.Scan(
			&i.ID,
			&i.VesselID,
			&i.VesselName,
			&i.RiskLevel,
			&i.LastInspectionDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePortCallZP21Seen = `-- name: UpdatePortCallZP21Seen :exec
UPDATE port_calls SET last_zp21_seen_at = $2 WHERE id = $1
`

type UpdatePortCallZP21SeenParams struct {
	ID             int64              `json:"id"`
	LastZp21SeenAt pgtype.Timestamptz `json:"last_zp21_seen_at"`
}

// Registra o timestamp do ciclo de scraping em que o port call foi visto.
func (q *Queries) UpdatePortCallZP21Seen(ctx context.Context, arg UpdatePortCallZP21SeenParams) error {
	_, err := q.db.Exec(ctx, updatePortCallZP21Seen, arg.ID, arg.LastZp21SeenAt)
	return err
}

const getLastZP21ScrapeTime = `-- name: GetLastZP21ScrapeTime :one
SELECT MAX(last_zp21_seen_at) FROM port_calls WHERE zp21_sourced = TRUE
`

// Retorna o timestamp do ciclo de scraping mais recente para filtro do dashboard.
func (q *Queries) GetLastZP21ScrapeTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastZP21ScrapeTime)
	var max pgtype.Timestamptz
	err := row.Scan(&max)
	return max, err
}

const getVesselsByName = `-- name: GetVesselsByName :many
SELECT id, imo, name, flag, year_built, vessel_type, length_m, beam_m, risk_level, last_inspection_date, created_at, updated_at, last_inspection_deficiencies, afretado, acompanhado FROM vessels WHERE name ILIKE $1 ORDER BY id
`

// Retorna todos os vessels com o nome dado (case-insensitive), incluindo não-acompanhados.
// Navios de estado (Marinha, etc.) ficam acompanhado=FALSE mas devem ser reconhecidos
// para evitar duplicatas. ORDER BY id prefere o registro mais antigo (manual).
func (q *Queries) GetVesselsByName(ctx context.Context, name string) ([]Vessel, error) {
	rows, err := q.db.Query(ctx, getVesselsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vessel{}
	for rows.Next() {
		var i Vessel
		if err := rows.Scan(
			&i.ID,
			&i.Imo,
			&i.Name,
			&i.Flag,
			&i.YearBuilt,
			&i.VesselType,
			&i.LengthM,
			&i.BeamM,
			&i.RiskLevel,
			&i.LastInspectionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastInspectionDeficiencies,
			&i.Afretado,
			&i.Acompanhado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardEntries = `-- name: ListDashboardEntries :many
SELECT
    v.id, v.name, v.imo, v.flag, v.length_m, v.beam_m, v.year_built,
    v.risk_level, v.last_inspection_date, v.last_inspection_deficiencies,
    v.afretado, v.acompanhado,
    pc.id          AS port_call_id,
    pc.terminal,
    pc.eta_date,
    pc.eta_time,
    pc.etd_date,
    pc.etd_time,
    pc.vessel_status,
    pc.port_call_status,
    pc.zp21_sourced,
    pc.last_zp21_seen_at,
    ins.id          AS inspection_id,
    ins.result      AS inspection_result
FROM vessels v
JOIN port_calls pc ON pc.vessel_id = v.id
LEFT JOIN inspections ins ON ins.port_call_id = pc.id
WHERE v.acompanhado = TRUE
  AND (pc.port_call_status = 'planned' OR pc.port_call_status = 'active')
  AND (
    (v.afretado = FALSE AND (v.flag IS NULL OR LOWER(TRIM(v.flag)) NOT IN ('brazil', 'brasil')))
    OR
    (v.last_inspection_deficiencies IS NOT NULL AND v.last_inspection_deficiencies != '')
  )
ORDER BY COALESCE(pc.eta_date, pc.etd_date) ASC NULLS LAST, v.name ASC
`

type ListDashboardEntriesRow struct {
	ID                         int64              `json:"id"`
	Name                       string             `json:"name"`
	Imo                        *string            `json:"imo"`
	Flag                       *string            `json:"flag"`
	LengthM                    pgtype.Numeric     `json:"length_m"`
	BeamM                      pgtype.Numeric     `json:"beam_m"`
	YearBuilt                  *int32             `json:"year_built"`
	RiskLevel                  *string            `json:"risk_level"`
	LastInspectionDate         pgtype.Date        `json:"last_inspection_date"`
	LastInspectionDeficiencies *string            `json:"last_inspection_deficiencies"`
	Afretado                   bool               `json:"afretado"`
	Acompanhado                bool               `json:"acompanhado"`
	PortCallID                 int64              `json:"port_call_id"`
	Terminal                   *string            `json:"terminal"`
	EtaDate                    pgtype.Date        `json:"eta_date"`
	EtaTime                    pgtype.Time        `json:"eta_time"`
	EtdDate                    pgtype.Date        `json:"etd_date"`
	EtdTime                    pgtype.Time        `json:"etd_time"`
	VesselStatus               string             `json:"vessel_status"`
	PortCallStatus             string             `json:"port_call_status"`
	Zp21Sourced                bool               `json:"zp21_sourced"`
	LastZp21SeenAt             pgtype.Timestamptz `json:"last_zp21_seen_at"`
	InspectionID               *int64             `json:"inspection_id"`
	InspectionResult           *string            `json:"inspection_result"`
}

// Retorna navios mercantes (ou sem categoria) com port calls ativos.
// NULL category aparece para alertar que o cadastro precisa ser completado.
// Ordenado por data (ETA ou ETD) — inspetores decidem com base no horário disponível.
func (q *Queries) ListDashboardEntries(ctx context.Context) ([]ListDashboardEntriesRow, error) {
	rows, err := q.db.Query(ctx, listDashboardEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDashboardEntriesRow{}
	for rows.Next() {
		var i ListDashboardEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Imo,
			&i.Flag,
			&i.LengthM,
			&i.BeamM,
			&i.YearBuilt,
			&i.RiskLevel,
			&i.LastInspectionDate,
			&i.LastInspectionDeficiencies,
			&i.Afretado,
			&i.Acompanhado,
			&i.PortCallID,
			&i.Terminal,
			&i.EtaDate,
			&i.EtaTime,
			&i.EtdDate,
			&i.EtdTime,
			&i.VesselStatus,
			&i.PortCallStatus,
			&i.Zp21Sourced,
			&i.LastZp21SeenAt,
			&i.InspectionID,
			&i.InspectionResult,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEscalas = `-- name: ListEscalas :many
SELECT
    pc.id, pc.vessel_id, pc.terminal,
    pc.eta_date, pc.etd_date,
    pc.actual_arrival, pc.actual_departure,
    pc.vessel_status, pc.port_call_status,
    pc.risk_level_snapshot, pc.priority_snapshot,
    v.name AS vessel_name, v.imo AS vessel_imo,
    v.flag AS vessel_flag, v.afretado AS vessel_afretado, v.acompanhado AS vessel_acompanhado,
    v.risk_level AS vessel_risk_level,
    v.last_inspection_date AS vessel_last_inspection_date,
    ins.id     AS inspection_id,
    ins.result AS inspection_result
FROM port_calls pc
JOIN vessels v ON v.id = pc.vessel_id
LEFT JOIN inspections ins ON ins.port_call_id = pc.id
WHERE ($1::text = '' OR pc.port_call_status = $1::text)
  AND ($2::bigint = 0 OR pc.vessel_id = $2::bigint)
  AND ($3::int = 0
       OR EXTRACT(YEAR FROM COALESCE(pc.actual_departure::date, pc.actual_arrival::date, pc.eta_date)) = $3::int)
  AND ($4::int = 0
       OR EXTRACT(MONTH FROM COALESCE(pc.actual_departure::date, pc.actual_arrival::date, pc.eta_date)) = $4::int)
ORDER BY COALESCE(pc.actual_departure::date, pc.actual_arrival::date, pc.eta_date) ASC NULLS LAST,
         pc.created_at ASC
`

type ListEscalasParams struct {
	Status   string `json:"status"`
	VesselID int64  `json:"vessel_id"`
	Year     int32  `json:"year"`
	Month    int32  `json:"month"`
}

type ListEscalasRow struct {
	ID                       int64              `json:"id"`
	VesselID                 int64              `json:"vessel_id"`
	Terminal                 *string            `json:"terminal"`
	EtaDate                  pgtype.Date        `json:"eta_date"`
	EtdDate                  pgtype.Date        `json:"etd_date"`
	ActualArrival            pgtype.Timestamptz `json:"actual_arrival"`
	ActualDeparture          pgtype.Timestamptz `json:"actual_departure"`
	VesselStatus             string             `json:"vessel_status"`
	PortCallStatus           string             `json:"port_call_status"`
	RiskLevelSnapshot        *string            `json:"risk_level_snapshot"`
	PrioritySnapshot         *string            `json:"priority_snapshot"`
	VesselName               string             `json:"vessel_name"`
	VesselImo                *string            `json:"vessel_imo"`
	VesselFlag               *string            `json:"vessel_flag"`
	VesselAfretado           bool               `json:"vessel_afretado"`
	VesselAcompanhado        bool               `json:"vessel_acompanhado"`
	VesselRiskLevel          *string            `json:"vessel_risk_level"`
	VesselLastInspectionDate pgtype.Date        `json:"vessel_last_inspection_date"`
	InspectionID             *int64             `json:"inspection_id"`
	InspectionResult         *string            `json:"inspection_result"`
}

// Lista todas as escalas com dados do navio e inspeção, ordenadas por data desc.
// Filtragem opcional por mês (0 = todos) e status (” = todos).
func (q *Queries) ListEscalas(ctx context.Context, arg ListEscalasParams) ([]ListEscalasRow, error) {
	rows, err := q.db.Query(ctx, listEscalas,
		arg.Status,
		arg.VesselID,
		arg.Year,
		arg.Month,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEscalasRow{}
	for rows.Next() {
		var i ListEscalasRow
		if err := rows.Scan(
			&i.ID,
			&i.VesselID,
			&i.Terminal,
			&i.EtaDate,
			&i.EtdDate,
			&i.ActualArrival,
			&i.ActualDeparture,
			&i.VesselStatus,
			&i.PortCallStatus,
			&i.RiskLevelSnapshot,
			&i.PrioritySnapshot,
			&i.VesselName,
			&i.VesselImo,
			&i.VesselFlag,
			&i.VesselAfretado,
			&i.VesselAcompanhado,
			&i.VesselRiskLevel,
			&i.VesselLastInspectionDate,
			&i.InspectionID,
			&i.InspectionResult,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEscalasByVessel = `-- name: ListEscalasByVessel :many
SELECT
    pc.id, pc.vessel_id, pc.terminal,
    pc.eta_date, pc.etd_date,
    pc.actual_arrival, pc.actual_departure,
    pc.vessel_status, pc.port_call_status,
    pc.risk_level_snapshot, pc.priority_snapshot,
    v.name AS vessel_name, v.imo AS vessel_imo,
    v.flag AS vessel_flag, v.afretado AS vessel_afretado, v.acompanhado AS vessel_acompanhado,
    v.risk_level AS vessel_risk_level,
    v.last_inspection_date AS vessel_last_inspection_date,
    ins.id     AS inspection_id,
    ins.result AS inspection_result
FROM port_calls pc
JOIN vessels v ON v.id = pc.vessel_id
LEFT JOIN inspections ins ON ins.port_call_id = pc.id
WHERE pc.vessel_id = $1
ORDER BY COALESCE(pc.actual_departure::date, pc.actual_arrival::date, pc.eta_date) DESC NULLS LAST,
         pc.created_at DESC
`

type ListEscalasByVesselRow struct {
	ID                       int64              `json:"id"`
	VesselID                 int64              `json:"vessel_id"`
	Terminal                 *string            `json:"terminal"`
	EtaDate                  pgtype.Date        `json:"eta_date"`
	EtdDate                  pgtype.Date        `json:"etd_date"`
	ActualArrival            pgtype.Timestamptz `json:"actual_arrival"`
	ActualDeparture          pgtype.Timestamptz `json:"actual_departure"`
	VesselStatus             string             `json:"vessel_status"`
	PortCallStatus           string             `json:"port_call_status"`
	RiskLevelSnapshot        *string            `json:"risk_level_snapshot"`
	PrioritySnapshot         *string            `json:"priority_snapshot"`
	VesselName               string             `json:"vessel_name"`
	VesselImo                *string            `json:"vessel_imo"`
	VesselFlag               *string            `json:"vessel_flag"`
	VesselAfretado           bool               `json:"vessel_afretado"`
	VesselAcompanhado        bool               `json:"vessel_acompanhado"`
	VesselRiskLevel          *string            `json:"vessel_risk_level"`
	VesselLastInspectionDate pgtype.Date        `json:"vessel_last_inspection_date"`
	InspectionID             *int64             `json:"inspection_id"`
	InspectionResult         *string            `json:"inspection_result"`
}

// Histórico de escalas de um navio específico, mais recentes primeiro.
func (q *Queries) ListEscalasByVessel(ctx context.Context, vesselID int64) ([]ListEscalasByVesselRow, error) {
	rows, err := q.db.Query(ctx, listEscalasByVessel, vesselID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEscalasByVesselRow{}
	for rows.Next() {
		var i ListEscalasByVesselRow
		if err := rows.Scan(
			&i.ID,
			&i.VesselID,
			&i.Terminal,
			&i.EtaDate,
			&i.EtdDate,
			&i.ActualArrival,
			&i.ActualDeparture,
			&i.VesselStatus,
			&i.PortCallStatus,
			&i.RiskLevelSnapshot,
			&i.PrioritySnapshot,
			&i.VesselName,
			&i.VesselImo,
			&i.VesselFlag,
			&i.VesselAfretado,
			&i.VesselAcompanhado,
			&i.VesselRiskLevel,
			&i.VesselLastInspectionDate,
			&i.InspectionID,
			&i.InspectionResult,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignPortCalls = `-- name: ReassignPortCalls :exec
UPDATE port_calls
SET vessel_id = $1
WHERE vessel_id = $2
`

type ReassignPortCallsParams struct {
	TargetID int64 `json:"target_id"`
	SourceID int64 `json:"source_id"`
}

// Transfere todos os port calls de um vessel para outro.
// Usado na operação de mesclar duplicatas.
func (q *Queries) ReassignPortCalls(ctx context.Context, arg ReassignPortCallsParams) error {
	_, err := q.db.Exec(ctx, reassignPortCalls, arg.TargetID, arg.SourceID)
	return err
}

const registerBerthing = `-- name: RegisterBerthing :exec
UPDATE port_calls
SET actual_arrival   = $2,
    vessel_status    = 'berthed',
    port_call_status = 'active',
    updated_at       = NOW()
WHERE id = $1
`

type RegisterBerthingParams struct {
	ID            int64              `json:"id"`
	ActualArrival pgtype.Timestamptz `json:"actual_arrival"`
}

// Registra a atracação efetiva: data real de chegada + muda status para ativo.
func (q *Queries) RegisterBerthing(ctx context.Context, arg RegisterBerthingParams) error {
	_, err := q.db.Exec(ctx, registerBerthing, arg.ID, arg.ActualArrival)
	return err
}

const registerDeparture = `-- name: RegisterDeparture :exec
UPDATE port_calls
SET actual_departure      = $2,
    port_call_status      = 'completed',
    risk_level_snapshot   = $3,
    priority_snapshot     = $4,
    updated_at            = NOW()
WHERE id = $1
`

type RegisterDepartureParams struct {
	ID                int64              `json:"id"`
	ActualDeparture   pgtype.Timestamptz `json:"actual_departure"`
	RiskLevelSnapshot *string            `json:"risk_level_snapshot"`
	PrioritySnapshot  *string            `json:"priority_snapshot"`
}

// Registra a partida efetiva: data real de saída + snapshot + conclui a escala.
func (q *Queries) RegisterDeparture(ctx context.Context, arg RegisterDepartureParams) error {
	_, err := q.db.Exec(ctx, registerDeparture,
		arg.ID,
		arg.ActualDeparture,
		arg.RiskLevelSnapshot,
		arg.PrioritySnapshot,
	)
	return err
}

const updatePortCallSnapshot = `-- name: UpdatePortCallSnapshot :exec
UPDATE port_calls
SET risk_level_snapshot = $2,
    priority_snapshot   = $3,
    updated_at          = NOW()
WHERE id = $1
`

type UpdatePortCallSnapshotParams struct {
	ID                int64   `json:"id"`
	RiskLevelSnapshot *string `json:"risk_level_snapshot"`
	PrioritySnapshot  *string `json:"priority_snapshot"`
}

func (q *Queries) UpdatePortCallSnapshot(ctx context.Context, arg UpdatePortCallSnapshotParams) error {
	_, err := q.db.Exec(ctx, updatePortCallSnapshot, arg.ID, arg.RiskLevelSnapshot, arg.PrioritySnapshot)
	return err
}

const updateBerthingDate = `-- name: UpdateBerthingDate :exec
UPDATE port_calls
SET actual_arrival   = $2,
    vessel_status    = 'berthed',
    port_call_status = 'active',
    updated_at       = NOW()
WHERE id = $1
`

type UpdateBerthingDateParams struct {
	ID            int64              `json:"id"`
	ActualArrival pgtype.Timestamptz `json:"actual_arrival"`
}

// Corrige a data de atracação manualmente (editores — sobrescreve dado automático).
func (q *Queries) UpdateBerthingDate(ctx context.Context, arg UpdateBerthingDateParams) error {
	_, err := q.db.Exec(ctx, updateBerthingDate, arg.ID, arg.ActualArrival)
	return err
}

const updateDepartureDate = `-- name: UpdateDepartureDate :exec
UPDATE port_calls
SET actual_departure = $2,
    updated_at       = NOW()
WHERE id = $1
`

type UpdateDepartureDateParams struct {
	ID              int64              `json:"id"`
	ActualDeparture pgtype.Timestamptz `json:"actual_departure"`
}

// Corrige a data de partida manualmente (editores — sobrescreve dado automático).
func (q *Queries) UpdateDepartureDate(ctx context.Context, arg UpdateDepartureDateParams) error {
	_, err := q.db.Exec(ctx, updateDepartureDate, arg.ID, arg.ActualDeparture)
	return err
}

const updatePortCallETA = `-- name: UpdatePortCallETA :exec
UPDATE port_calls
SET eta_date  = $2,
    eta_time  = $3,
    terminal  = COALESCE($4, terminal),
    updated_at = NOW()
WHERE id = $1
`

type UpdatePortCallETAParams struct {
	ID       int64       `json:"id"`
	EtaDate  pgtype.Date `json:"eta_date"`
	EtaTime  pgtype.Time `json:"eta_time"`
	Terminal *string     `json:"terminal"`
}

// Atualiza a previsão de chegada e o terminal a partir de uma linha de entrada do ZP-21.
// COALESCE mantém o terminal existente se o novo for NULL.
func (q *Queries) UpdatePortCallETA(ctx context.Context, arg UpdatePortCallETAParams) error {
	_, err := q.db.Exec(ctx, updatePortCallETA,
		arg.ID,
		arg.EtaDate,
		arg.EtaTime,
		arg.Terminal,
	)
	return err
}

const updatePortCallETD = `-- name: UpdatePortCallETD :exec
UPDATE port_calls
SET etd_date  = $2,
    etd_time  = $3,
    terminal  = COALESCE($4, terminal),
    updated_at = NOW()
WHERE id = $1
`

type UpdatePortCallETDParams struct {
	ID       int64       `json:"id"`
	EtdDate  pgtype.Date `json:"etd_date"`
	EtdTime  pgtype.Time `json:"etd_time"`
	Terminal *string     `json:"terminal"`
}

// Atualiza a previsão de saída a partir de uma linha de saída do ZP-21.
// COALESCE mantém o terminal existente se o novo for NULL.
func (q *Queries) UpdatePortCallETD(ctx context.Context, arg UpdatePortCallETDParams) error {
	_, err := q.db.Exec(ctx, updatePortCallETD,
		arg.ID,
		arg.EtdDate,
		arg.EtdTime,
		arg.Terminal,
	)
	return err
}

const updatePortCallFull = `-- name: UpdatePortCallFull :exec
UPDATE port_calls
SET terminal            = $2,
    eta_date            = $3,
    eta_time            = $4,
    etd_date            = $5,
    etd_time            = $6,
    actual_arrival      = $7,
    actual_departure    = $8,
    port_call_status    = $9,
    risk_level_snapshot = $10,
    priority_snapshot   = $11,
    vessel_status       = CASE WHEN $7::timestamptz IS NOT NULL THEN 'berthed' ELSE 'navigating' END,
    updated_at          = NOW()
WHERE id = $1
`

type UpdatePortCallFullParams struct {
	ID                int64              `json:"id"`
	Terminal          *string            `json:"terminal"`
	EtaDate           pgtype.Date        `json:"eta_date"`
	EtaTime           pgtype.Time        `json:"eta_time"`
	EtdDate           pgtype.Date        `json:"etd_date"`
	EtdTime           pgtype.Time        `json:"etd_time"`
	ActualArrival     pgtype.Timestamptz `json:"actual_arrival"`
	ActualDeparture   pgtype.Timestamptz `json:"actual_departure"`
	PortCallStatus    string             `json:"port_call_status"`
	RiskLevelSnapshot *string            `json:"risk_level_snapshot"`
	PrioritySnapshot  *string            `json:"priority_snapshot"`
}

// Edição completa de uma escala pelo usuário.
func (q *Queries) UpdatePortCallFull(ctx context.Context, arg UpdatePortCallFullParams) error {
	_, err := q.db.Exec(ctx, updatePortCallFull,
		arg.ID,
		arg.Terminal,
		arg.EtaDate,
		arg.EtaTime,
		arg.EtdDate,
		arg.EtdTime,
		arg.ActualArrival,
		arg.ActualDeparture,
		arg.PortCallStatus,
		arg.RiskLevelSnapshot,
		arg.PrioritySnapshot,
	)
	return err
}

const listReportEntries = `-- name: ListReportEntries :many
WITH period_vessels AS (
    SELECT pc.id, pc.vessel_id,
           pc.actual_arrival::date AS arrival_date
    FROM port_calls pc
    JOIN vessels v ON v.id = pc.vessel_id
    WHERE v.acompanhado = TRUE
      AND pc.actual_arrival IS NOT NULL
      AND EXTRACT(YEAR  FROM pc.actual_arrival::date) = $1::int
      AND EXTRACT(MONTH FROM pc.actual_arrival::date) = $2::int
),
vessel_first_arrival AS (
    SELECT vessel_id, MIN(arrival_date) AS first_arrival
    FROM period_vessels
    GROUP BY vessel_id
),
ranked AS (
    SELECT
        pc.id, pc.vessel_id, pc.terminal,
        pc.eta_date, pc.etd_date,
        pc.actual_arrival, pc.actual_departure,
        pc.port_call_status, pc.risk_level_snapshot, pc.priority_snapshot,
        v.name AS vessel_name, v.imo AS vessel_imo, v.flag AS vessel_flag,
        v.afretado AS vessel_afretado, v.year_built AS vessel_year_built,
        v.vessel_type AS vessel_type,
        ins.id AS inspection_id, ins.result AS inspection_result, ins.inspection_date,
        vfa.first_arrival,
        ROW_NUMBER() OVER (
            PARTITION BY pc.vessel_id
            ORDER BY pc.actual_arrival DESC NULLS LAST
        ) AS rn
    FROM period_vessels pv
    JOIN port_calls pc ON pc.id = pv.id
    JOIN vessels v ON v.id = pc.vessel_id
    JOIN vessel_first_arrival vfa ON vfa.vessel_id = pc.vessel_id
    LEFT JOIN inspections ins ON ins.port_call_id = pc.id
)
SELECT id, vessel_id, terminal, eta_date, etd_date,
       actual_arrival, actual_departure, port_call_status,
       risk_level_snapshot, priority_snapshot,
       vessel_name, vessel_imo, vessel_flag, vessel_afretado,
       vessel_year_built, vessel_type,
       inspection_id, inspection_result, inspection_date
FROM ranked
WHERE rn = 1
ORDER BY
    CASE WHEN vessel_afretado = FALSE
              AND (vessel_flag IS NULL OR LOWER(TRIM(vessel_flag)) NOT IN ('brazil','brasil'))
         THEN 0 ELSE 1 END ASC,
    actual_arrival ASC NULLS LAST,
    vessel_name ASC
`

type ListReportEntriesParams struct {
	Year  int32 `json:"year"`
	Month int32 `json:"month"`
}

type ListReportEntriesRow struct {
	ID                int64              `json:"id"`
	VesselID          int64              `json:"vessel_id"`
	Terminal          *string            `json:"terminal"`
	EtaDate           pgtype.Date        `json:"eta_date"`
	EtdDate           pgtype.Date        `json:"etd_date"`
	ActualArrival     pgtype.Timestamptz `json:"actual_arrival"`
	ActualDeparture   pgtype.Timestamptz `json:"actual_departure"`
	PortCallStatus    string             `json:"port_call_status"`
	RiskLevelSnapshot *string            `json:"risk_level_snapshot"`
	PrioritySnapshot  *string            `json:"priority_snapshot"`
	VesselName        string             `json:"vessel_name"`
	VesselImo         *string            `json:"vessel_imo"`
	VesselFlag        *string            `json:"vessel_flag"`
	VesselAfretado    bool               `json:"vessel_afretado"`
	VesselYearBuilt   *int32             `json:"vessel_year_built"`
	VesselType        *string            `json:"vessel_type"`
	InspectionID     *int64      `json:"inspection_id"`
	InspectionResult *string    `json:"inspection_result"`
	InspectionDate   pgtype.Date `json:"inspection_date"`
}

// Retorna escalas que tocaram o porto no mês selecionado, para o relatório mensal.
func (q *Queries) ListReportEntries(ctx context.Context, arg ListReportEntriesParams) ([]ListReportEntriesRow, error) {
	rows, err := q.db.Query(ctx, listReportEntries, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportEntriesRow{}
	for rows.Next() {
		var i ListReportEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.VesselID,
			&i.Terminal,
			&i.EtaDate,
			&i.EtdDate,
			&i.ActualArrival,
			&i.ActualDeparture,
			&i.PortCallStatus,
			&i.RiskLevelSnapshot,
			&i.PrioritySnapshot,
			&i.VesselName,
			&i.VesselImo,
			&i.VesselFlag,
			&i.VesselAfretado,
			&i.VesselYearBuilt,
			&i.VesselType,
			&i.InspectionID,
			&i.InspectionResult,
			&i.InspectionDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countReportKPI = `-- name: CountReportKPI :one
SELECT
    COUNT(pc.id) AS total_porto,
    COUNT(pc.id) FILTER (
        WHERE v.afretado = FALSE
          AND (v.flag IS NULL OR LOWER(TRIM(v.flag)) NOT IN ('brazil','brasil'))
    ) AS estrangeiros,
    COUNT(pc.id) FILTER (
        WHERE v.afretado = FALSE
          AND (v.flag IS NULL OR LOWER(TRIM(v.flag)) NOT IN ('brazil','brasil'))
          AND (pc.priority_snapshot IN ('P1','P2') OR ins.id IS NOT NULL)
    ) AS sujeitos,
    COUNT(ins.id) FILTER (
        WHERE v.afretado = FALSE
          AND (v.flag IS NULL OR LOWER(TRIM(v.flag)) NOT IN ('brazil','brasil'))
    ) AS inspected
FROM port_calls pc
JOIN vessels v ON v.id = pc.vessel_id
LEFT JOIN inspections ins ON ins.port_call_id = pc.id
WHERE v.acompanhado = TRUE
  AND pc.actual_arrival IS NOT NULL
  AND EXTRACT(YEAR  FROM pc.actual_arrival::date) = $1::int
  AND EXTRACT(MONTH FROM pc.actual_arrival::date) = $2::int
`

type CountReportKPIParams struct {
	Year  int32 `json:"year"`
	Month int32 `json:"month"`
}

type CountReportKPIRow struct {
	TotalPorto   int64 `json:"total_porto"`
	Estrangeiros int64 `json:"estrangeiros"`
	Sujeitos     int64 `json:"sujeitos"`
	Inspected    int64 `json:"inspected"`
}

func (q *Queries) CountReportKPI(ctx context.Context, arg CountReportKPIParams) (CountReportKPIRow, error) {
	row := q.db.QueryRow(ctx, countReportKPI, arg.Year, arg.Month)
	var i CountReportKPIRow
	err := row.Scan(&i.TotalPorto, &i.Estrangeiros, &i.Sujeitos, &i.Inspected)
	return i, err
}

const countEscalas = `-- name: CountEscalas :one
SELECT COUNT(*)::int
FROM port_calls pc
JOIN vessels v ON v.id = pc.vessel_id
WHERE ($1::text = '' OR pc.port_call_status = $1::text)
  AND ($2::bigint = 0 OR pc.vessel_id = $2::bigint)
  AND ($3::int = 0
       OR EXTRACT(YEAR FROM COALESCE(pc.actual_departure::date, pc.actual_arrival::date, pc.eta_date)) = $3::int)
  AND ($4::int = 0
       OR EXTRACT(MONTH FROM COALESCE(pc.actual_departure::date, pc.actual_arrival::date, pc.eta_date)) = $4::int)
`

type CountEscalasParams struct {
	Status   string `json:"status"`
	VesselID int64  `json:"vessel_id"`
	Year     int32  `json:"year"`
	Month    int32  `json:"month"`
}

func (q *Queries) CountEscalas(ctx context.Context, arg CountEscalasParams) (int32, error) {
	row := q.db.QueryRow(ctx, countEscalas, arg.Status, arg.VesselID, arg.Year, arg.Month)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const listEscalasPaged = `-- name: ListEscalasPaged :many
SELECT
    pc.id, pc.vessel_id, pc.terminal,
    pc.eta_date, pc.etd_date,
    pc.actual_arrival, pc.actual_departure,
    pc.vessel_status, pc.port_call_status,
    pc.risk_level_snapshot, pc.priority_snapshot,
    v.name AS vessel_name, v.imo AS vessel_imo,
    v.flag AS vessel_flag, v.afretado AS vessel_afretado, v.acompanhado AS vessel_acompanhado,
    v.risk_level AS vessel_risk_level,
    v.last_inspection_date AS vessel_last_inspection_date,
    ins.id     AS inspection_id,
    ins.result AS inspection_result
FROM port_calls pc
JOIN vessels v ON v.id = pc.vessel_id
LEFT JOIN inspections ins ON ins.port_call_id = pc.id
WHERE ($1::text = '' OR pc.port_call_status = $1::text)
  AND ($2::bigint = 0 OR pc.vessel_id = $2::bigint)
  AND ($3::int = 0
       OR EXTRACT(YEAR FROM COALESCE(pc.actual_departure::date, pc.actual_arrival::date, pc.eta_date)) = $3::int)
  AND ($4::int = 0
       OR EXTRACT(MONTH FROM COALESCE(pc.actual_departure::date, pc.actual_arrival::date, pc.eta_date)) = $4::int)
ORDER BY COALESCE(pc.actual_departure::date, pc.actual_arrival::date, pc.eta_date) ASC NULLS LAST,
         pc.created_at ASC
LIMIT 50 OFFSET $5
`

type ListEscalasPagedParams struct {
	Status   string `json:"status"`
	VesselID int64  `json:"vessel_id"`
	Year     int32  `json:"year"`
	Month    int32  `json:"month"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListEscalasPaged(ctx context.Context, arg ListEscalasPagedParams) ([]ListEscalasRow, error) {
	rows, err := q.db.Query(ctx, listEscalasPaged,
		arg.Status, arg.VesselID, arg.Year, arg.Month, arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEscalasRow{}
	for rows.Next() {
		var i ListEscalasRow
		if err := rows.Scan(
			&i.ID, &i.VesselID, &i.Terminal,
			&i.EtaDate, &i.EtdDate,
			&i.ActualArrival, &i.ActualDeparture,
			&i.VesselStatus, &i.PortCallStatus,
			&i.RiskLevelSnapshot, &i.PrioritySnapshot,
			&i.VesselName, &i.VesselImo,
			&i.VesselFlag, &i.VesselAfretado, &i.VesselAcompanhado,
			&i.VesselRiskLevel, &i.VesselLastInspectionDate,
			&i.InspectionID, &i.InspectionResult,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
