// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scraper_run.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertScraperRun = `-- name: InsertScraperRun :exec
INSERT INTO scraper_runs (scraper, started_at, finished_at, duration_ms, status,
                          rows_found, items_processed, items_failed, error_message)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertScraperRunParams struct {
	Scraper        string             `json:"scraper"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	DurationMs     int32              `json:"duration_ms"`
	Status         string             `json:"status"`
	RowsFound      int32              `json:"rows_found"`
	ItemsProcessed int32              `json:"items_processed"`
	ItemsFailed    int32              `json:"items_failed"`
	ErrorMessage   *string            `json:"error_message"`
}

func (q *Queries) InsertScraperRun(ctx context.Context, arg InsertScraperRunParams) error {
	_, err := q.db.Exec(ctx, insertScraperRun,
		arg.Scraper, arg.StartedAt, arg.FinishedAt, arg.DurationMs, arg.Status,
		arg.RowsFound, arg.ItemsProcessed, arg.ItemsFailed, arg.ErrorMessage,
	)
	return err
}

const listRecentScraperRuns = `-- name: ListRecentScraperRuns :many
SELECT id, scraper, started_at, finished_at, duration_ms, status, rows_found, items_processed, items_failed, error_message FROM scraper_runs
WHERE scraper = $1
ORDER BY started_at DESC
LIMIT 50
`

func (q *Queries) ListRecentScraperRuns(ctx context.Context, scraper string) ([]ScraperRun, error) {
	rows, err := q.db.Query(ctx, listRecentScraperRuns, scraper)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScraperRun{}
	for rows.Next() {
		var i ScraperRun
		if err := rows.Scan(
			&i.ID, &i.Scraper, &i.StartedAt, &i.FinishedAt, &i.DurationMs,
			&i.Status, &i.RowsFound, &i.ItemsProcessed, &i.ItemsFailed, &i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countConsecutiveErrors = `-- name: CountConsecutiveErrors :one
SELECT COUNT(*)::int FROM (
    SELECT status FROM scraper_runs
    WHERE scraper = $1
    ORDER BY started_at DESC
    LIMIT 10
) recent
WHERE status = 'error'
`

func (q *Queries) CountConsecutiveErrors(ctx context.Context, scraper string) (int32, error) {
	row := q.db.QueryRow(ctx, countConsecutiveErrors, scraper)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getLatestRunPerScraper = `-- name: GetLatestRunPerScraper :many
SELECT DISTINCT ON (scraper) id, scraper, started_at, finished_at, duration_ms, status, rows_found, items_processed, items_failed, error_message
FROM scraper_runs
ORDER BY scraper, started_at DESC
`

func (q *Queries) GetLatestRunPerScraper(ctx context.Context) ([]ScraperRun, error) {
	rows, err := q.db.Query(ctx, getLatestRunPerScraper)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScraperRun{}
	for rows.Next() {
		var i ScraperRun
		if err := rows.Scan(
			&i.ID, &i.Scraper, &i.StartedAt, &i.FinishedAt, &i.DurationMs,
			&i.Status, &i.RowsFound, &i.ItemsProcessed, &i.ItemsFailed, &i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listRecentRuns = `-- name: ListRecentRuns :many
SELECT id, scraper, started_at, finished_at, duration_ms, status, rows_found, items_processed, items_failed, error_message FROM scraper_runs
ORDER BY started_at DESC
LIMIT 20
`

func (q *Queries) ListRecentRuns(ctx context.Context) ([]ScraperRun, error) {
	rows, err := q.db.Query(ctx, listRecentRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScraperRun{}
	for rows.Next() {
		var i ScraperRun
		if err := rows.Scan(
			&i.ID, &i.Scraper, &i.StartedAt, &i.FinishedAt, &i.DurationMs,
			&i.Status, &i.RowsFound, &i.ItemsProcessed, &i.ItemsFailed, &i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countZP21SilentCycles = `-- name: CountZP21SilentCycles :one
SELECT COUNT(*)::int FROM (
    SELECT rows_found FROM scraper_runs
    WHERE scraper = 'zp21'
    ORDER BY started_at DESC
    LIMIT 3
) last3
WHERE rows_found = 0
`

func (q *Queries) CountZP21SilentCycles(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countZP21SilentCycles)
	var count int32
	err := row.Scan(&count)
	return count, err
}
