// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vessel.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVessel = `-- name: CreateVessel :one
INSERT INTO vessels (imo, name, flag, year_built, vessel_type, length_m, beam_m)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, imo, name, flag, year_built, vessel_type, length_m, beam_m, risk_level, last_inspection_date, active, created_at, updated_at
`

type CreateVesselParams struct {
	Imo        string         `json:"imo"`
	Name       string         `json:"name"`
	Flag       *string        `json:"flag"`
	YearBuilt  *int32         `json:"year_built"`
	VesselType *string        `json:"vessel_type"`
	LengthM    pgtype.Numeric `json:"length_m"`
	BeamM      pgtype.Numeric `json:"beam_m"`
}

// Cria novo navio. risk_level e last_inspection_date não são incluídos —
// chegam posteriormente via scraping do CIALA.
func (q *Queries) CreateVessel(ctx context.Context, arg CreateVesselParams) (Vessel, error) {
	row := q.db.QueryRow(ctx, createVessel,
		arg.Imo,
		arg.Name,
		arg.Flag,
		arg.YearBuilt,
		arg.VesselType,
		arg.LengthM,
		arg.BeamM,
	)
	var i Vessel
	err := row.Scan(
		&i.ID,
		&i.Imo,
		&i.Name,
		&i.Flag,
		&i.YearBuilt,
		&i.VesselType,
		&i.LengthM,
		&i.BeamM,
		&i.RiskLevel,
		&i.LastInspectionDate,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateVessel = `-- name: DeactivateVessel :exec
UPDATE vessels
SET active = false, updated_at = NOW()
WHERE id = $1
`

// Soft delete: marca como inativo sem deletar o registro.
// Preserva histórico de port_calls e inspeções vinculadas.
func (q *Queries) DeactivateVessel(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateVessel, id)
	return err
}

const getVessel = `-- name: GetVessel :one
SELECT id, imo, name, flag, year_built, vessel_type, length_m, beam_m,
       risk_level, last_inspection_date, active, created_at, updated_at
FROM vessels
WHERE id = $1
`

// Busca um navio pelo ID (ativo ou não — usado em detalhes e edição).
func (q *Queries) GetVessel(ctx context.Context, id int64) (Vessel, error) {
	row := q.db.QueryRow(ctx, getVessel, id)
	var i Vessel
	err := row.Scan(
		&i.ID,
		&i.Imo,
		&i.Name,
		&i.Flag,
		&i.YearBuilt,
		&i.VesselType,
		&i.LengthM,
		&i.BeamM,
		&i.RiskLevel,
		&i.LastInspectionDate,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVesselByIMO = `-- name: GetVesselByIMO :one
SELECT id, imo, name, flag, year_built, vessel_type, length_m, beam_m,
       risk_level, last_inspection_date, active, created_at, updated_at
FROM vessels
WHERE imo = $1
`

// Busca por IMO — usado pelo scraper para evitar cadastros duplicados.
func (q *Queries) GetVesselByIMO(ctx context.Context, imo string) (Vessel, error) {
	row := q.db.QueryRow(ctx, getVesselByIMO, imo)
	var i Vessel
	err := row.Scan(
		&i.ID,
		&i.Imo,
		&i.Name,
		&i.Flag,
		&i.YearBuilt,
		&i.VesselType,
		&i.LengthM,
		&i.BeamM,
		&i.RiskLevel,
		&i.LastInspectionDate,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVessels = `-- name: ListVessels :many

SELECT id, imo, name, flag, year_built, vessel_type, length_m, beam_m,
       risk_level, last_inspection_date, active, created_at, updated_at
FROM vessels
WHERE active = true
ORDER BY name
`

// Queries de Vessel para o sqlc.
//
// O sqlc lê estes comentários especiais para saber o nome da função Go
// e o tipo de retorno que deve gerar:
//
//	:one   → retorna uma linha (Row) ou erro pgx.ErrNoRows
//	:many  → retorna um slice []Vessel
//	:exec  → não retorna linhas (UPDATE/DELETE sem RETURNING)
//
// Lista todos os navios ativos ordenados por nome.
func (q *Queries) ListVessels(ctx context.Context) ([]Vessel, error) {
	rows, err := q.db.Query(ctx, listVessels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vessel{}
	for rows.Next() {
		var i Vessel
		if err := rows.Scan(
			&i.ID,
			&i.Imo,
			&i.Name,
			&i.Flag,
			&i.YearBuilt,
			&i.VesselType,
			&i.LengthM,
			&i.BeamM,
			&i.RiskLevel,
			&i.LastInspectionDate,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVessel = `-- name: UpdateVessel :one
UPDATE vessels
SET name        = $2,
    flag        = $3,
    year_built  = $4,
    vessel_type = $5,
    length_m    = $6,
    beam_m      = $7,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, imo, name, flag, year_built, vessel_type, length_m, beam_m, risk_level, last_inspection_date, active, created_at, updated_at
`

type UpdateVesselParams struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	Flag       *string        `json:"flag"`
	YearBuilt  *int32         `json:"year_built"`
	VesselType *string        `json:"vessel_type"`
	LengthM    pgtype.Numeric `json:"length_m"`
	BeamM      pgtype.Numeric `json:"beam_m"`
}

// Atualiza campos editáveis pelo usuário. risk_level e last_inspection_date
// são atualizados apenas pelo scraper (Story 2.x), não aqui.
func (q *Queries) UpdateVessel(ctx context.Context, arg UpdateVesselParams) (Vessel, error) {
	row := q.db.QueryRow(ctx, updateVessel,
		arg.ID,
		arg.Name,
		arg.Flag,
		arg.YearBuilt,
		arg.VesselType,
		arg.LengthM,
		arg.BeamM,
	)
	var i Vessel
	err := row.Scan(
		&i.ID,
		&i.Imo,
		&i.Name,
		&i.Flag,
		&i.YearBuilt,
		&i.VesselType,
		&i.LengthM,
		&i.BeamM,
		&i.RiskLevel,
		&i.LastInspectionDate,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
